title: "Codebook: Software Development Resources"
email: codebook@andychase.me
description: Software Development Resources
baseurl: ""
url: "https://codebook.snc.io"
twitter_username: techstoreclub
github_username:  techstoreclub

markdown: kramdown
# For the icons next to links
resource_type_to_icon_map:
  guide: ss-signpost
  opinion: ss-chat
  "yes": ss-check
  "no": ss-delete
permalink: pretty
collections:
  topics:
    output: true
  infos:
    output: true
