title: "Codebook: Software Development Resources"
email: codebook@andychase.me
description: Software Development Resources
baseurl: ""
url: "https://codebook.snc.io"
footer: |
  * [<span class="t">Tech</span><span class="s">Store</span><span class="c">Club</span>](https://techstore.club)
  * [About](/about)[Terms](/about/terms)[Privacy](/about/privacy)
  * [(CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)

markdown: kramdown
# For the icons next to links
resource_type_to_icon_map:
  guide: ss-signpost
  opinion: ss-chat
  "yes": ss-check
  "no": ss-delete
permalink: pretty
collections:
  topics:
    output: true
  infos:
    output: true
