allowed_icons = {
    'cursor', 'crosshair', 'search', 'zoomin', 'zoomout', 'view', 'attach', 'link', 'move', 'write', 'writingdisabled',
    'erase', 'compose', 'lock', 'unlock', 'key', 'backspace', 'ban', 'trash', 'target', 'tag', 'bookmark', 'flag',
    'dislike', 'heart', 'halfheart', 'star', 'halfstar', 'sample', 'crop', 'layers', 'fill', 'stroke', 'phone',
    'phonedisabled', 'rss', 'facetime', 'reply', 'send', 'mail', 'inbox', 'chat', 'ellipsischat', 'ellipsis', 'user',
    'femaleuser', 'users', 'cart', 'creditcard', 'dollarsign', 'barchart', 'piechart', 'box', 'home', 'buildings',
    'warehouse', 'globe', 'navigate', 'compass', 'signpost', 'map', 'location', 'pin', 'database', 'hdd', 'music',
    'volume', 'lowvolume', 'highvolume', 'airplay', 'camera', 'picture', 'video', 'play', 'pause', 'stop', 'record',
    'rewind', 'fastforward', 'skipback', 'skipforward', 'eject', 'repeat', 'replay', 'shuffle', 'book', 'openbook',
    'notebook', 'newspaper', 'grid', 'rows', 'columns', 'thumbnails', 'filter', 'desktop', 'laptop', 'tablet', 'cell',
    'battery', 'highbattery', 'mediumbattery', 'lowbattery', 'emptybattery', 'lightbulb', 'downloadcloud', 'download',
    'uploadcloud', 'upload', 'fork', 'merge', 'transfer', 'refresh', 'sync', 'loading', 'wifi', 'connection', 'file',
    'folder', 'quote', 'text', 'font', 'print', 'fax', 'list', 'layout', 'action', 'redirect', 'expand', 'contract',
    'help', 'info', 'alert', 'caution', 'logout', 'plus', 'hyphen', 'check', 'delete', 'settings', 'dashboard',
    'notifications', 'notificationsdisabled', 'clock', 'stopwatch', 'calendar', 'addcalendar', 'removecalendar',
    'checkcalendar', 'deletecalendar', 'plane', 'briefcase', 'cloud', 'droplet', 'flask', 'up', 'upright', 'right',
    'downright', 'down', 'downleft', 'left', 'upleft', 'navigateup', 'navigateright', 'navigatedown', 'navigateleft',
    'directup', 'directright', 'dropdown', 'directleft', 'retweet', 'mic', 'like',
}
