title: "Codebook: The best links and books on programming"
email: codebook@andychase.me
description: A curated list of the best programming links & books, ordered topically
baseurl: ""
url: "https://codebook.snc.io"
footer: |
  * [<span class="t">Tech</span><span class="s">Store</span><span class="c">Club</span>](https://techstore.club)
  * [About](/about)[Terms](/about/terms)[Privacy](/about/privacy)[Source](//github.com/techstoreclub/codebook)
  * [(CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)

markdown: kramdown
# For the icons next to links
resource_type_to_icon_map:
  guide: ss-signpost
  opinion: ss-chat
  info: ss-info
  data: ss-barchart
  "yes": ss-check
  "no": ss-delete
permalink: pretty
collections:
  topics:
    output: true
  infos:
    output: true

kramdown:
  auto_ids:       true
  footnote_nr:    1
  toc_levels:     1..3
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
