title: "Codebook: The best links and books on programming"
email: codebook@andychase.me
description: A curated list of the best programming links & books, ordered topically
baseurl: ""
url: "https://codebook.snc.io"
footer: |
  * [<span class="t">Tech</span><span class="s">Store</span><span class="c">Club</span>](https://techstore.club)
  * [About](/about/about)[Terms](/about/terms)[Privacy](/about/privacy)[Source](//github.com/techstoreclub/codebook)
  * [(CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)

resource_type_to_icon_map:
  guide: ss-signpost
  opinion: ss-chat
  info: ss-info
  data: ss-barchart
  "yes": ss-check
  "no": ss-delete
info:
  about: About Codebook
  terms: Terms of Use
  privacy: Privacy Policy
